## Nama : M. Arvin Saskoro
## NIM : 2109106048
## Kelas : Informatika A2 21

In [41]:
import tensorflow as tf

### Create Random Tensor 

In [42]:
random_tensor = tf.random.normal([5,5], mean = 5, stddev = 1)
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[6.1062603, 6.4610124, 3.7857468, 5.7985277, 5.56736  ],
       [3.581728 , 5.1960773, 3.982624 , 4.374564 , 5.1403136],
       [5.138782 , 4.7797604, 3.3930943, 4.2583537, 4.0098276],
       [5.3088903, 6.071995 , 4.80572  , 4.3322344, 4.9571342],
       [4.111652 , 3.4733233, 4.321433 , 5.552151 , 3.9584675]],
      dtype=float32)>

### Create Tensor from List 

In [43]:
list = [[2,3,5,7,11],
       [29,23,19,17,13],
       [31,37,41,43,47],
       [71,67,61,59,53],
       [73,79,83,89,97]]
prime_tensor = tf.convert_to_tensor(list, dtype = tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [29., 23., 19., 17., 13.],
       [31., 37., 41., 43., 47.],
       [71., 67., 61., 59., 53.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

### Menampilkan Dimensi Kedua Tensor Diatas

In [44]:
print('Dimensi Random Tensor : ', random_tensor.shape)
print('Dimensi Prime Tensor  : ', prime_tensor.shape)

Dimensi Random Tensor :  (5, 5)
Dimensi Prime Tensor  :  (5, 5)


### Perhitungan Aritmatika 2 Variabel

In [50]:
print("Penambahan :\n" ,tf.add(random_tensor,prime_tensor).numpy())
print("\nPengurangan :\n" ,tf.subtract(random_tensor,prime_tensor).numpy())
print("\nPerkalian :\n" ,tf.matmul(random_tensor,prime_tensor).numpy())
print("\nPembagian :\n" ,tf.divide(random_tensor,prime_tensor).numpy())
print("\nPerpangkatan :\n" ,tf.pow(prime_tensor,random_tensor).numpy())

Penambahan :
 [[  8.10626    9.461012   8.785747  12.798528  16.56736 ]
 [ 32.581726  28.196077  22.982624  21.374565  18.140314]
 [ 36.138783  41.779762  44.393093  47.258354  51.009827]
 [ 76.30889   73.07199   65.80572   63.332233  57.957134]
 [ 77.11165   82.47332   87.321434  94.552155 100.958466]]

Pengurangan :
 [[  4.1062603   3.4610124  -1.2142532  -1.2014723  -5.43264  ]
 [-25.418272  -17.803923  -15.017376  -12.625436   -7.8596864]
 [-25.861217  -32.220238  -37.606907  -38.741646  -42.990173 ]
 [-65.69111   -60.928005  -56.19428   -54.667767  -48.042866 ]
 [-68.88835   -75.52668   -78.678566  -83.447845  -93.041534 ]]

Perkalian :
 [[1135.0527  1135.3175  1124.3073  1152.9763  1176.448  ]
 [ 967.148    976.79266  973.41614 1000.2454  1024.5938 ]
 [ 849.1371   852.9814   848.2015   871.248    892.785  ]
 [1005.1424  1015.26746 1014.65533 1043.8188  1073.653  ]
 [ 926.08496  936.82745  930.9642   953.5302   971.7241 ]]

Pembagian :
 [[3.0531301  2.1536708  0.75714934 0.8283611

### Menampilkan Nilai MAX dan MIN random_tensor

In [46]:
max_all = tf.math.reduce_max(random_tensor)
print('Nilai Maximal : ', max_all.numpy())

min_all = tf.math.reduce_min(random_tensor)
print('Nilai Minimal :', min_all.numpy())

Nilai Maximal :  6.4610124
Nilai Minimal : 3.3930943


### Concatenation Random_tensor dengan Prime Tensor

In [47]:
concate = tf.concat([random_tensor, prime_tensor],axis = 1)
concate.numpy()

array([[ 6.1062603,  6.4610124,  3.7857468,  5.7985277,  5.56736  ,
         2.       ,  3.       ,  5.       ,  7.       , 11.       ],
       [ 3.581728 ,  5.1960773,  3.982624 ,  4.374564 ,  5.1403136,
        29.       , 23.       , 19.       , 17.       , 13.       ],
       [ 5.138782 ,  4.7797604,  3.3930943,  4.2583537,  4.0098276,
        31.       , 37.       , 41.       , 43.       , 47.       ],
       [ 5.3088903,  6.071995 ,  4.80572  ,  4.3322344,  4.9571342,
        71.       , 67.       , 61.       , 59.       , 53.       ],
       [ 4.111652 ,  3.4733233,  4.321433 ,  5.552151 ,  3.9584675,
        73.       , 79.       , 83.       , 89.       , 97.       ]],
      dtype=float32)

### Hasil Sorting

In [48]:
print("Concatenation Sort Descending :\n",tf.sort(concate,direction="DESCENDING").numpy())

Concatenation Sort Descending :
 [[11.         7.         6.4610124  6.1062603  5.7985277  5.56736
   5.         3.7857468  3.         2.       ]
 [29.        23.        19.        17.        13.         5.1960773
   5.1403136  4.374564   3.982624   3.581728 ]
 [47.        43.        41.        37.        31.         5.138782
   4.7797604  4.2583537  4.0098276  3.3930943]
 [71.        67.        61.        59.        53.         6.071995
   5.3088903  4.9571342  4.80572    4.3322344]
 [97.        89.        83.        79.        73.         5.552151
   4.321433   4.111652   3.9584675  3.4733233]]


In [49]:
print("Random_Tensor Sort Descending :\n", tf.sort(random_tensor, direction = "DESCENDING").numpy())
print("\nPrime_Tensor Sort Descending :\n", tf.sort(prime_tensor, direction = "DESCENDING").numpy())

Random_Tensor Sort Descending :
 [[6.4610124 6.1062603 5.7985277 5.56736   3.7857468]
 [5.1960773 5.1403136 4.374564  3.982624  3.581728 ]
 [5.138782  4.7797604 4.2583537 4.0098276 3.3930943]
 [6.071995  5.3088903 4.9571342 4.80572   4.3322344]
 [5.552151  4.321433  4.111652  3.9584675 3.4733233]]

Prime_Tensor Sort Descending :
 [[11.  7.  5.  3.  2.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]]
